### ISSUE TITLE
links to geojason.io

### ISSUE THREAD

**Issue by evanwill** [ssimpkin/dhsite2017#1]
Links to geojason.io in the [previewing with geojason.io](https://ssimpkin.github.io/dhsite2017/csv-to-geojson/#previewing-with-geojson-io) section are given as `https://geojson.io/`. However, geojason.io is not https, so browsers give a scary warning when trying to open the link. Changing the links to `http://geojson.io/` avoids this issue.

Great resource, thanks!

**Comment by ssimpkin** [comment]
I'm so sorry I missed this for *checks date* almost an entire year! I've gone ahead and made the change to http to avoid the scary message. Thanks for the suggestion!
